import React, { useState } from 'react';
import { X, Mail, Send, Copy, Check, Sparkles, Loader2, CalendarPlus, CheckCircle2 } from 'lucide-react';
import { api } from '../services/api.ts';
import type { ClinicalNote, FollowUpEmail } from '../types/index.ts';

interface FollowUpEmailModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (draft: FollowUpEmail) => void;
  initialNote?: ClinicalNote;
}

export const FollowUpEmailModal: React.FC<FollowUpEmailModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  initialNote
}) => {
  const [patientName, setPatientName] = useState(initialNote?.patientName || 'David Chen');
  const [patientEmail, setPatientEmail] = useState('dchen.tech@gmail.com');
  const [carePlanSummary, setCarePlanSummary] = useState(
    initialNote 
      ? `SOAP Assessment: ${initialNote.soap.assessment}\nPlan: ${initialNote.soap.plan}\nDiet: ${initialNote.dietAndLifestyleOrders}\nRx: ${initialNote.prescriptions.join(', ')}`
      : 'HbA1c optimization: Switch to Metformin ER 750mg with dinner and start Empagliflozin 10mg daily. Restrict carbohydrates to <50g per meal, add 35g fiber daily, maintain 450 kcal deficit. Next appointment in 4 weeks for fasting labs.'
  );
  const [nextAppointmentDate, setNextAppointmentDate] = useState('2024-11-20');

  const [isLoading, setIsLoading] = useState(false);
  const [generatedDraft, setGeneratedDraft] = useState<FollowUpEmail | null>(null);
  const [copied, setCopied] = useState(false);
  const [dispatched, setDispatched] = useState(false);

  if (!isOpen) return null;

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!patientName.trim() || isLoading) return;

    setIsLoading(true);
    try {
      const draft = await api.draftFollowUpEmail({
        patientName,
        patientEmail,
        carePlanSummary,
        nextAppointmentDate
      });
      setGeneratedDraft(draft);
      onSuccess(draft);
    } catch (err: any) {
      console.error('Error drafting email:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = () => {
    if (!generatedDraft) return;
    navigator.clipboard.writeText(generatedDraft.body);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDispatch = async () => {
    if (!generatedDraft) return;
    setIsLoading(true);
    try {
      await api.dispatchEmail(generatedDraft.id);
      setDispatched(true);
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-2 sm:p-4 overscroll-contain">
      <div className="bg-[#0e1320] border border-slate-800 rounded-2xl w-full max-w-2xl max-h-[92dvh] sm:max-h-[90vh] flex flex-col overflow-hidden shadow-2xl animate-in fade-in zoom-in-95">
        
        {/* Header */}
        <div className="p-3.5 sm:p-4 border-b border-slate-800 flex items-center justify-between bg-[#0a0e17] shrink-0">
          <div className="flex items-center gap-2.5 min-w-0">
            <div className="p-2 rounded-xl bg-cyan-600/20 text-cyan-400 border border-cyan-500/30 shrink-0">
              <Mail className="w-4 h-4" />
            </div>
            <div className="min-w-0">
              <h3 className="text-sm font-bold text-white truncate">Draft Appointment Follow-up Email</h3>
              <p className="text-[11px] text-slate-400 font-mono truncate">
                Empathetic, clear patient communication generated by Aura AI
              </p>
            </div>
          </div>
          <button 
            type="button"
            onClick={onClose}
            aria-label="Close modal"
            className="p-2.5 min-h-[44px] min-w-[44px] flex items-center justify-center rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 active:scale-95 transition-all shrink-0 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {generatedDraft ? (
            <div className="space-y-4">
              <div className="flex items-center justify-between p-3 rounded-lg bg-emerald-950/60 border border-emerald-800/80 text-xs text-emerald-300">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Follow-up email drafted and linked to patient calendar!</span>
                </div>
                {dispatched && (
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-900 text-emerald-200">
                    Dispatched
                  </span>
                )}
              </div>

              <div className="space-y-3 text-xs">
                <div>
                  <span className="text-[10px] uppercase font-mono text-slate-400 block mb-1">Subject</span>
                  <input
                    type="text"
                    value={generatedDraft.subject}
                    onChange={(e) => setGeneratedDraft({ ...generatedDraft, subject: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-base sm:text-xs text-white min-h-[44px] focus:outline-none focus:border-cyan-500"
                  />
                </div>

                <div>
                  <span className="text-[10px] uppercase font-mono text-slate-400 block mb-1">Body</span>
                  <textarea
                    value={generatedDraft.body}
                    onChange={(e) => setGeneratedDraft({ ...generatedDraft, body: e.target.value })}
                    rows={10}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3.5 text-base sm:text-xs text-slate-200 leading-relaxed font-sans focus:outline-none focus:border-cyan-500"
                  />
                </div>
              </div>

              {/* Action buttons */}
              <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-2 border-t border-slate-800">
                <button
                  type="button"
                  onClick={handleCopy}
                  className="px-4 py-2.5 min-h-[44px] rounded-xl bg-slate-800 hover:bg-slate-700 active:scale-95 text-slate-200 text-xs font-medium flex items-center justify-center gap-2 transition-all cursor-pointer"
                >
                  {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                  <span>{copied ? 'Copied to Clipboard' : 'Copy Email Text'}</span>
                </button>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={onClose}
                    className="flex-1 sm:flex-initial px-4 py-2.5 min-h-[44px] rounded-xl bg-slate-800 hover:bg-slate-700 active:scale-95 text-slate-300 text-xs transition-colors cursor-pointer"
                  >
                    Done
                  </button>

                  <button
                    type="button"
                    onClick={handleDispatch}
                    disabled={isLoading || dispatched}
                    className="flex-1 sm:flex-initial px-5 py-2.5 min-h-[44px] rounded-xl bg-indigo-600 hover:bg-indigo-500 active:scale-95 disabled:opacity-50 text-white text-xs font-semibold flex items-center justify-center gap-2 transition-all shadow-md shadow-indigo-900/30 cursor-pointer"
                  >
                    <Send className="w-4 h-4" />
                    <span>{dispatched ? 'Dispatched!' : 'Send Email to Patient'}</span>
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <form onSubmit={handleGenerate} className="space-y-4 text-xs">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="text-[10px] uppercase font-mono text-slate-400 block mb-1">Patient Name</label>
                  <input
                    type="text"
                    value={patientName}
                    onChange={(e) => setPatientName(e.target.value)}
                    required
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-base sm:text-xs text-white min-h-[44px] focus:outline-none focus:border-cyan-500"
                  />
                </div>

                <div>
                  <label className="text-[10px] uppercase font-mono text-slate-400 block mb-1">Patient Email</label>
                  <input
                    type="email"
                    value={patientEmail}
                    onChange={(e) => setPatientEmail(e.target.value)}
                    required
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-base sm:text-xs text-white min-h-[44px] focus:outline-none focus:border-cyan-500"
                  />
                </div>
              </div>

              <div>
                <label className="text-[10px] uppercase font-mono text-slate-400 block mb-1">
                  Next Follow-up Appointment Window
                </label>
                <input
                  type="date"
                  value={nextAppointmentDate}
                  onChange={(e) => setNextAppointmentDate(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-base sm:text-xs text-white font-mono min-h-[44px] focus:outline-none focus:border-cyan-500"
                />
              </div>

              <div>
                <label className="text-[10px] uppercase font-mono text-slate-400 block mb-1">
                  Clinical Care Plan, Prescriptions, & Lifestyle Orders
                </label>
                <textarea
                  value={carePlanSummary}
                  onChange={(e) => setCarePlanSummary(e.target.value)}
                  rows={6}
                  required
                  placeholder="Outline diagnosis, medication instructions, and diet/exercise goals..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3.5 text-base sm:text-xs text-white focus:outline-none focus:border-cyan-500 leading-relaxed font-sans"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-800">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2.5 min-h-[44px] rounded-xl bg-slate-800 hover:bg-slate-700 active:scale-95 text-slate-300 text-xs transition-colors cursor-pointer"
                >
                  Cancel
                </button>

                <button
                  type="submit"
                  disabled={isLoading}
                  className="px-5 py-2.5 min-h-[44px] rounded-xl bg-cyan-600 hover:bg-cyan-500 active:scale-95 disabled:opacity-50 text-white text-xs font-semibold flex items-center gap-2 transition-all shadow-md shadow-cyan-950/40 cursor-pointer"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      <span>Drafting Email with AI...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      <span>Generate AI Follow-up Email</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
};
